apiVersion: v1
kind: Pod
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  containers:
    - name: order-service
      image: order-service:1.0
      ports:
        - containerPort: 8083
      env:
        # ===============================
        # DATABASE CONFIG (MYSQL)
        # ===============================
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/order_command_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: ""

        # ===============================
        # MONGODB CONFIG
        # ===============================
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://mongodb-service:27017/order_query_db"

        # ===============================
        # KAFKA CONFIG
        # ===============================
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-service:9092"

        # ===============================
        # EUREKA CLIENT
        # ===============================
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eureka-service:8761/eureka/"

      imagePullPolicy: Never # Karena image dibuat lokal (Docker Desktop / Kind)