spring:
  application:
    name: PEMINJAMAN-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/peminjaman_db
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ================= KAFKA CONFIG =================
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      # Group ID digunakan oleh KafkaListener
      group-id: peminjaman-service-group
      auto-offset-reset: earliest

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

server:
  port: 8083

# Konfigurasi Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
